name: Build and Deploy Code

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  netlifybuild:
    name: Build and Deploy For Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn

      - run: yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1